### ISSUE TITLE
Warning: Unknown props `events`, `options` on <select> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

### ISSUE THREAD

**Issue by MrCsabaToth** [luqin/react-select2#1]
```
        <Select2
            className="form-control"
            value={this.state.selections.metrics}
            data={this.props.widgetData.choices.metric_choices}
            onSelect={this.onMetricsSelected}
            options={{
              placeholder: 'Search Metric...',
            }}
        />
```

**Comment by MrCsabaToth** [comment]
![react_select2_1](https://cloud.githubusercontent.com/assets/744949/18375661/2469d2f2-760d-11e6-90fa-d09232210eae.jpg)

**Comment by MrCsabaToth** [comment]
The screenshot: the select2 module doesn't show the regular form but it is off-placed out of the popup. I'm not sure if the error message relates to this, but there's a good chance. I tried `react-select2-wrapper` too, same thing.

**Comment by joetidee** [comment]
I am getting this error too :(
I'm using React v15.3.2

**Comment by welcoMattic** [comment]
ping @luqin https://facebook.github.io/react/warnings/unknown-prop.html
