### ISSUE TITLE
How to force select2 to be open on init?

### ISSUE THREAD

**Issue by ghost** [luqin/react-select2#4]
Hi,

After searching, I still cannot find out how to force select2 to init 'opened'... I guess this is something to pass on options, but what?
Thx in advance for your help.

**Comment by luqin** [comment]
[Access to select2](https://github.com/luqin/react-select2#access-to-select2) 
Then you can use all of select2's APIs

**Comment by ghost** [comment]
Ok thanks. I did a component for the select2 wrapper, and then in the `componentDidMount`, I used the `select2('open')`... And voilà! :relieved: Thx
