### ISSUE TITLE
4.0.2 webpack error

### ISSUE THREAD

**Issue by dwightee** [luqin/react-select2#6]
I installed the new version, because 4.0.1 is not supporting onChange for deleting an option for multiple select, but I get this error

ERROR in ./~/react-select2/lib/components/Select2.js
Module not found: Error: Cannot resolve module 'react/lib/DOMProperty' in /opt/smoke/md/static/node_modules/react-select2/lib/components
 @ ./~/react-select2/lib/components/Select2.js 17:19-51

ERROR in ./~/react-select2/lib/components/Select2.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginRegistry' in /opt/smoke/md/static/node_modules/react-select2/lib/components
 @ ./~/react-select2/lib/components/Select2.js 21:27-67
Child extract-text-webpack-plugin:
        + 16 hidden modules

**Comment by luqin** [comment]
React@15.4.0: [React package and browser build no longer "secretly" includes React DOM.](https://github.com/facebook/react/blob/master/CHANGELOG.md#1540-november-16-2016)

**Comment by lukebatchelor** [comment]
Just came here to report the same thing.

It looks like the methods you need are in react-dom though https://unpkg.com/react-dom@15.4.0/dist/react-dom.js

Not sure if they are exposed or not, but that should be a good starting place.

For anyone else, I'm currently working around it by pinning react and react-dom to 15.3.0.

**Comment by lukebatchelor** [comment]
Looked it up out of curiosity, you should be able to 

```
import { DOMProperty, EventPluginRegistry } from 'react-dom';
```

**Comment by luqin** [comment]
```
 react-select2@4.0.3
```
